name: deploy_frontend
# Deploys frontend folder changes
on:
  push:
    branches: [main]
    paths: "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload to blob storage
        run: |
          az storage blob upload-batch --account-name azurecvibrahim --auth-mode key -d '$web' -s frontend/ --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}

      - name: Purge CDN endpoint
        run: |
          az cdn endpoint purge --content-paths "/*" --profile-name "mycvsite" --name "mycvsite" --resource-group "azure-resume-rg" --account-key ${{ secrets.AZURE_ACCOUNT_KEY }}

      # Azure logout (optional, since we're not logging in)
      - name: logout
        run: |
          az logout
        if: always()
